### ISSUE TITLE
Gio GLiB import error, missing dependancy?

### ISSUE THREAD

**Issue by eskalVAR** [un-def/i3blocks-spotify-persist#8]
The script has recently stopped working with latest python / arch linux updates?

Any clues as to what dependencies are missing / what the issue could be?

Error log:

Traceback (most recent call last):
  File "/home/viking/.local/bin/i3blocks-mpris", line 5, in <module>
    from i3blocks_mpris import _main
  File "/home/viking/.local/lib/python3.10/site-packages/i3blocks_mpris.py", line 11, in <module>
    from gi.repository import Gio, GLib
  File "/home/viking/.local/lib/python3.10/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /home/viking/.local/lib/python3.10/site-packages/gi/_gi.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_AsStringAndSize

**Comment by eskalVAR** [comment]
For future, I uninstalled pycairo, PYGObject dbus-python using pip then re-installed. This fixed the issue.
